# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentgate" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "e22d757325fb1434a969360c6fb533377c2ab05d67d4159627174fb751eaf9e4"
      url "https://github.com/bnymnDev/agentgate/releases/download/v#{version}/agentgate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7d34f1fc6888e42540ee300a3bb0dae57c616ef3acf8ce7ce8394f5fbaf4b1c2"
      url "https://github.com/bnymnDev/agentgate/releases/download/v#{version}/agentgate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2b7a158dccc1640a2746176c4f86b5e6b9bccafbf46b5adbf5f6ddc8f70056ea"
      url "https://github.com/bnymnDev/agentgate/releases/download/v#{version}/agentgate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "942bd68e4756781e35ff37aa3a778c7607d2c29f3e39f2b11d8cbaf2734171b0"
      url "https://github.com/bnymnDev/agentgate/releases/download/v#{version}/agentgate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentgate"
  desc "Firewall, kill switch and flight recorder for your AI agent's tools"
  homepage "https://github.com/bnymnDev/agentgate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentgate"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentgate"]
    end
  end

  # No zap stanza required
end
