# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentgate" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "061764cd12fcca9ae5ba532e1184a00846bea9bd97750e9c6edf5d8e3d7710ee"
      url "https://github.com/bnymnDev/agentgate/releases/download/v#{version}/agentgate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "49fc769fdabafa0e9f448a629de62c213857833ca0d921779aeb73192c253d93"
      url "https://github.com/bnymnDev/agentgate/releases/download/v#{version}/agentgate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8c0be4f238f16951c7c965fb92faabe441b50d8310dd110c3d563200edf9b701"
      url "https://github.com/bnymnDev/agentgate/releases/download/v#{version}/agentgate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4544dbc8b0deaf6fd090047c12a6e62159306b6d160f081d825aac0667d8cef8"
      url "https://github.com/bnymnDev/agentgate/releases/download/v#{version}/agentgate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentgate"
  desc "Firewall, tripwires and flight recorder for your AI agent's tools"
  homepage "https://github.com/bnymnDev/agentgate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentgate"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentgate"]
    end
  end

  # No zap stanza required
end
