# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentgate" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "bd9bf904208d2df09c9e05459ac6a34be6b47d2d8d2347a1531c194a72cd441c"
      url "https://github.com/bnymnDev/agentgate/releases/download/v#{version}/agentgate_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f686ddcc77b49524ea95dc71957b344ba8ef41c74f9e1ce53b64b0421c8d7353"
      url "https://github.com/bnymnDev/agentgate/releases/download/v#{version}/agentgate_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a79b776d837691df60456419cbf7ed4426861bef6c4ffa5cf7c111d60bfacd47"
      url "https://github.com/bnymnDev/agentgate/releases/download/v#{version}/agentgate_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7da625028035fe728750c17e8dacb1093c52bbf331e16ed111df78a88cc35879"
      url "https://github.com/bnymnDev/agentgate/releases/download/v#{version}/agentgate_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentgate"
  desc "Firewall, kill switch and flight recorder for your AI agent's tools"
  homepage "https://github.com/bnymnDev/agentgate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentgate"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentgate"]
    end
  end

  # No zap stanza required
end
